### PR TITLE
Set default display to block for selected icon checkmark

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/vaadin-context-menu/issues/152

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/31)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-item/31#-:-LAmPQyQAkI6qNTPDcLP:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-item.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-item/31#-LAqMHAS1jq68wiN2lbv:-LAqMHATBwiAB6jVAeom:b-1y3no5) ([raw file](https://github.com/vaadin/vaadin-item/blob/9e7e978f2308e2c1ec6ac9fda417a596c86e5d8f/theme/lumo/vaadin-item.html#L26)):*
> ```HTML
>       /* Selectable items have a checkmark icon */
>       :host([tabindex])::before {
>         display: var(--_lumo-item-selected-icon-display, block);
> ```

I don't think we can just change the default from none to block here. This should still default to none, but list-box could make it block by default in its context.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/31)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-item.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-item/31#-LAqMHAS1jq68wiN2lbv:-LAqN4Gz7EpC9ruJdssE:bmz83qc) ([raw file](https://github.com/vaadin/vaadin-item/blob/9e7e978f2308e2c1ec6ac9fda417a596c86e5d8f/theme/lumo/vaadin-item.html#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I don't think we can just change the default from none to block here. This should still default to none, but list-box could make it block by default in its context.
</blockquote></details>

So, in list-box: --_lumo-item-selected-icon-display: var(--_lumo-list-box-item-selected-icon-display, block);

And then context menu could assign --_lumo-list-box-item-selected-icon-display to none

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/31)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-item.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-item/31#-LAqMHAS1jq68wiN2lbv:-LAqiNUm6X8hTzkyxY4-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-item/blob/9e7e978f2308e2c1ec6ac9fda417a596c86e5d8f/theme/lumo/vaadin-item.html#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

So, in list-box: --_lumo-item-selected-icon-display: var(--_lumo-list-box-item-selected-icon-display, block);

And then context menu could assign --_lumo-list-box-item-selected-icon-display to none
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/31)*

**Pull request closed without merging**
