### PR TITLE
Moved ItemMixin from vaadin-list-mixin repository

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-core/issues/105

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/4)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-item-mixin.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxI78ysFwDwvXEy6LmE:-KxI78ysFwDwvXEy6LmF:b11qtg4) ([raw file](https://github.com/vaadin/vaadin-item/blob/b72db130a98a2b906bc3a6aadf4e58e81e076e97/vaadin-item-mixin.html#L40)):*
> ```HTML
> 
>         /**
>          * If true, the button is in the selected state.
> ```

nit: `The item is in selected state`.
General question: Can we move this selected state part and accessibility `aria-selected` to `ListMixin`?
Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-:-KxI7xk_UIpXOJIjmdqA:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-item-mixin.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxI78ysFwDwvXEy6LmE:-KxIFCKVWGtKRWumSuaZ:b-23jihw) ([raw file](https://github.com/vaadin/vaadin-item/blob/b72db130a98a2b906bc3a6aadf4e58e81e076e97/vaadin-item-mixin.html#L40)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

nit: `The item is in selected state`.
General question: Can we move this selected state part and accessibility `aria-selected` to `ListMixin`?
Not a blocker.
</blockquote></details>

We (@tomivirkki) already talked about this. The problem is that we want the item to offer a CSS API for those statuses, so makes not sense that the element does not have it.
We have moved all the logic related of how and when selection can be performed to container mixin.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/4)*

**Comment by tomivirkki** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/vaadin-item-mixin.html, line 61 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxIPlgzTnu0eDqjG96l:-KxIPlgzTnu0eDqjG96m:b-8kj9pw) ([raw file](https://github.com/vaadin/vaadin-item/blob/8c79919f6401ded7d77d6f5b47d1061f90389229/test/vaadin-item-mixin.html#L61)):*
> ```HTML
>     }
> 
>     describe('vaadin-list-item-mixin', () => {
> ```

item-mixin

---

*[test/vaadin-item.html, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxIQ3KYk5yaIS3V4uMv:-KxIQ3KYk5yaIS3V4uMw:b-8kj9pw) ([raw file](https://github.com/vaadin/vaadin-item/blob/8c79919f6401ded7d77d6f5b47d1061f90389229/test/vaadin-item.html#L27)):*
> ```HTML
>       });
> 
>       it('should extend list-item-mixin', () => {
> ```

item-mixin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/4)*

**Comment by manolo** [comment]
Review status: 8 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-item-mixin.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxI78ysFwDwvXEy6LmE:-KxITdc9jFE5QFaV83cf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-item/blob/b72db130a98a2b906bc3a6aadf4e58e81e076e97/vaadin-item-mixin.html#L40)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We (@tomivirkki) already talked about this. The problem is that we want the item to offer a CSS API for those statuses, so makes not sense that the element does not have it.
We have moved all the logic related of how and when selection can be performed to container mixin.
</blockquote></details>

Done.

---

*[test/vaadin-item-mixin.html, line 61 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxIPlgzTnu0eDqjG96l:-KxITcXOmbkgtpysiUJU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-item/blob/8c79919f6401ded7d77d6f5b47d1061f90389229/test/vaadin-item-mixin.html#L61)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

item-mixin
</blockquote></details>

Done.

---

*[test/vaadin-item.html, line 27 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-KxIQ3KYk5yaIS3V4uMv:-KxITcy70qSuATFe2Jpg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-item/blob/8c79919f6401ded7d77d6f5b47d1061f90389229/test/vaadin-item.html#L27)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

item-mixin
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/4)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 9 of 12 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/4#-:-KxIVN5ESmaXLDQic1Eg:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/4)*

**Pull request merged**
