### PR TITLE
Not fire click on keyup if  not active.

### PR DESCRIPTION
**Pull request by manolo**
Fixes  https://github.com/vaadin/vaadin-dropdown-menu/issues/11

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/6)

### CODE REVIEW

**Comment by manolo** [comment]
Note that this was a regression introduced in https://github.com/vaadin/vaadin-tabs/commit/ee9ca823#diff-9eeb799b822a1c18cabfd6b1e559e165R108 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-:-Kxi-E6MxhXsVCYGgz0W:b-o5xzz2)*

**Comment by tomivirkki** [comment]
*[test/vaadin-item-mixin.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-KxlPtlxaQFbzzQGMAgt:-KxlPtlxaQFbzzQGMAgu:bdmfyrk) ([raw file](https://github.com/vaadin/vaadin-item/blob/f89fce4509cb3a4fde7fe9bc99f7f1e2bf6e2efa/test/vaadin-item-mixin.html#L164)):*
> ```HTML
>       it('should not fire click event if keyup does not happen after a keydown in the element', () => {
>         item.addEventListener('click', () => {
>           throw new Error('click fired!');
> ```

Throwing an exception is not a good practice for asserting in tests. Use Sinon instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6)*

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-item-mixin.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-KxlPtlxaQFbzzQGMAgt:-KxmEWvD6FZDeIc5fTTT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-item/blob/f89fce4509cb3a4fde7fe9bc99f7f1e2bf6e2efa/test/vaadin-item-mixin.html#L164)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Throwing an exception is not a good practice for asserting in tests. Use Sinon instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6)*

**Comment by YuriyVaadin** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-item-mixin.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-KxlPtlxaQFbzzQGMAgt:-KxmNcSG77qNIjDh4bl1:b-cth452) ([raw file](https://github.com/vaadin/vaadin-item/blob/f89fce4509cb3a4fde7fe9bc99f7f1e2bf6e2efa/test/vaadin-item-mixin.html#L164)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think it's missing event listener for the Sinon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6)*

**Comment by tomivirkki** [comment]
*[test/vaadin-item-mixin.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-KxlPtlxaQFbzzQGMAgt:-KxmapzB6pNcDeuTJAJx:b-crn10v) ([raw file](https://github.com/vaadin/vaadin-item/blob/f89fce4509cb3a4fde7fe9bc99f7f1e2bf6e2efa/test/vaadin-item-mixin.html#L164)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

I think it's missing event listener for the Sinon.
</blockquote></details>

Yuriy is right, the spy is never registered as the listener

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-item-mixin.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-KxlPtlxaQFbzzQGMAgt:-Kxmg6BSQYgG-cz19iaT:b-f4cgul) ([raw file](https://github.com/vaadin/vaadin-item/blob/f89fce4509cb3a4fde7fe9bc99f7f1e2bf6e2efa/test/vaadin-item-mixin.html#L164)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yuriy is right, the spy is never registered as the listener
</blockquote></details>

Ups. Good catch, Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/6#-:-Kxmh_Vkjue14S4JQ3XK:bnfp4nl)*

**Pull request merged**
