### PR TITLE
Add a vlue property to item

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-dropdown-menu/issues/15

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-item/7)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Update analysis.json, other than that :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/7#-:-Ky0fNTwFNdP4XEMdPBQ:b-p66paq)*

**Comment by manolo** [comment]
Done

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/7#-:-Ky0mTreNiLYBX1DIeAs:bb6un1j)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/7)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-item/7#-:-Ky0ogSd9cXf6RjexVJS:bnfp4nl)*

**Pull request merged**
